forのtoyを作成
lifeistech/toybox pull request #105
Opened 2022-07-16 03:42 UTC by risako070310

Closes #52

2022-07-16 05:37 UTC, kyoya1123 commented
@risako070310
コメントしました！

@MasakazOzaki @nokonoko2057 
forEach系の関数のをこのtoyに含めて良いか議論したいです

2022-07-16 08:27 UTC, MasakazOzaki reviewed
これもはやenumのtoyな気がしてきたんだけどどうだろう🧐
すごく網羅されているんだけどこれはenumのtoyな気がしてきたぞ

2022-07-16 08:27 UTC, MasakazOzaki commented on for/for/ViewController.swift
> +
```suggestion
        }
```

2022-07-16 14:15 UTC, nokonoko2057 commented
@risako070310 @MasakazOzaki @kyoya1123 
うおー！しっかり網羅的な対応ありがとうー！

forEachについては入れておいて良いと思うー
$0 についてはコメントつけておきたいし、
fore Eachは`for i in 1...10 {` のiと一緒だよーと書いておきたい
printはもう少し区別つくようにしたいかなー。`print("i >> \(i)")` とか

enumまわりについてはenumの印象が強いね
方向性としてはこの辺があると思ってて、個人的には2がいいかなーと思った！

1. enumをなくして、forとforEachに絞る
  - enumのforはenumのtoyでやる
2. enumのprintはtitleなどの変数をなくして、StringでforEachする
  - ボタンを押したら、printくらいのシンプルさにする
 

```swift
enum Transportation: String, CaseIterable {
    case bus
    case train
    case airplane
}
```

3. 今のまま行く

2022-07-19 11:30 UTC, nokonoko2057 commented
@risako070310 2で！

2022-07-31 05:28 UTC, MasakazOzaki commented
@risako070310 こちらお願いいたしますー！

2022-08-03 01:44 UTC, risako070310 commented
@MasakazOzaki @nokonoko2057 
こちら更新いたしました！レビューお願いいたします 10706cd6c140b67bf178077823362746616f26d7

2022-08-03 01:53 UTC, nokonoko2057 approved these changes
@risako070310 対応ありがとうー！

2022-08-03 12:58 UTC, MasakazOzaki reviewed
@risako070310 
修正ありがとう！
細かいところですが修正お願いいたします！

2022-08-03 12:58 UTC, MasakazOzaki commented on for/for/ViewController.swift
> +            print("i >> \(i)")
@risako070310 Swiftでは矢印は `->`で表す慣習があります。`→`でもOKです。少しわかりやすいようにこちらに変更をお願いいたします！

2022-08-03 12:58 UTC, MasakazOzaki commented on for/for/ViewController.swift
> +            print("i >> \($0)")
@risako070310 forEachでは要素ひとつを`i`とは表さないのでここは変更をお願いいたします！単に要素だけprintでも全然良きです！

2022-08-03 12:58 UTC, MasakazOzaki commented on for/for/ViewController.swift
>          for i in 1...10{
とても細かいところで申し訳ないんだけど、Swiftでは中括弧の前はスペースを一つ開けるという慣習があります><


```suggestion
        for i in 1...10 {
```

2022-08-04 13:56 UTC, MasakazOzaki requested changes
@risako070310 追加のレビューで申し訳ない！こちら対応お願いいたします！

2022-08-04 13:56 UTC, MasakazOzaki commented on for/for/ViewController.swift
> +
@risako070310 細かいですが、ここのwhitespaceも削除していきたいです><><

2022-08-04 13:56 UTC, MasakazOzaki commented on for/for/ViewController.swift
> +                    self.transportationLabel.text = "\(transportation.rawValue)が選択されました"
クロージャの中でselfをキャプチャする場合は循環参照を防ぐために`[weak self]`を使って弱参照にしてあげると良きです

```suggestion
                menuItems.append(UIAction(title: transportation.rawValue) { [weak self] _ in
                    self.transportationLabel.text = "\(transportation.rawValue)が選択されました"
```

2022-08-04 13:56 UTC, MasakazOzaki commented on for/for/Transportation.swift
> +import UIKit
@risako070310 すごく細かいところなんだけど、ここではUIKitの機能は使わずSwift Standard Libraryのみの機能を使っているので`import UIKit`は削除してしまいましょう！
ちなみに`import UIKit`をするときはFoundationを内部的に呼んでいるので`import Foundation`は記述不要です。
```suggestion
```

2022-08-06 03:23 UTC, risako070310 commented
@MasakazOzaki こちらも改めてレビューお願いします><

2022-08-06 03:33 UTC, MasakazOzaki approved these changes
LGTM！
修正お疲れ様でした！
ありがとう！🎉

2022-08-06 03:33 UTC, merged