Feature/optional
lifeistech/toybox pull request #110
Opened 2022-07-26 14:27 UTC by kyoya1123

#59

2022-07-31 05:30 UTC, MasakazOzaki approved these changes
LGTM!とてもよくまとめられていると思います！ありがとう！

2022-07-31 05:30 UTC, MasakazOzaki commented
@nokonoko2057 こちらもレビューよろしくお願いいたします

2022-07-31 06:33 UTC, nokonoko2057 reviewed
@kyoya1123 内容めちゃいいです！optionalでどんなものが出てくるだろうと思ったけど、optionalの扱い方が網羅されたいい感じのになってると思いやす！
2点コメントしたのでよろしくですー！

2022-07-31 06:33 UTC, nokonoko2057 commented on Optional/Optional/ViewController.swift
> +        resultLabel.text = String(number!)
numberがnilの時はクラッシュするコメントを追加したいっす！

2022-07-31 06:33 UTC, nokonoko2057 commented on Optional/Optional/ViewController.swift
> +    }
@kyoya1123 本質的ではない修正になってしまうんだけど、
switchNilAndSomeの関数はviewDidLoadの下(L12くらい) に配置したいっす！

コードを読みにきた人が「お、switchでなんかした時はnumberの数値が変わってそう。nilってのがあるな」と思わせてから他のコードを読んだの方が理解が進みやすいかなと思ったので！

2022-08-04 14:00 UTC, MasakazOzaki requested changes
コメントしました。のこのこさんの通りに修正をお願い意します！

2022-08-04 14:00 UTC, MasakazOzaki commented on Optional/Optional/ViewController.swift
> +    }
確かに

2022-08-05 05:36 UTC, kyoya1123 commented
@MasakazOzaki 
コメント箇所修正しました！
確認お願いします

2022-08-05 05:36 UTC, MasakazOzaki approved these changes
LGTM! 何度も修正ありがとうございました！

2022-08-05 05:37 UTC, merged