delegateのtoyを作成
lifeistech/toybox pull request #129
Opened 2022-08-06 02:43 UTC by risako070310

Closed #56

2022-08-06 03:58 UTC, MasakazOzaki requested changes
@risako070310 PRありがとう！とてもよくできています！少し修正して欲しい箇所があるので確認と修正お願いいたします！

2022-08-06 03:58 UTC, MasakazOzaki commented on delegate/delegate/CollectionViewCell.swift
> +        fruitButton.layer.cornerRadius = 5
@risako070310 awakeFromNibはViewControllerでいうところのViewDidLoadに当たるので、このような見た目の調整はdidSetに書いた方が綺麗になるので移動していただけると助かりーみんです！

あと慣習として数値を指定する場合は8の倍数、8じゃ大きすぎるときは4とか2を使うことが多いのですが、cornerRadiusを5にしているのは意図があったりするのかな？

8の倍数のするのは世の中の他のものも大体8の倍数でできていて人が見慣れているので違和感が少なく見えるという利点があります。

2022-08-06 03:58 UTC, MasakazOzaki commented on delegate/delegate/CollectionViewCell.swift
> +
@risako070310 ここの空白は1行で大丈夫なので一つ消しちゃいましょう！

2022-08-06 03:58 UTC, MasakazOzaki commented on delegate/delegate/CollectionViewCell.swift
> +        cellDone?()
@risako070310 このcellDoneにVoidを流してるのは何をやっているんだろう、、🧐

2022-08-06 03:58 UTC, MasakazOzaki commented on delegate/delegate/CollectionViewCell.swift
> +    @IBAction func buttonTapAction(_ sender: Any) {
@risako070310 funcの命名ですが、swift(私が今まで見てきた)では`buttonTapAction`などとせずに`buttonTapped()`, `buttonPressed()`などとしている場合が多いです。
ちなみに私は以前Appleの裏側のソースコード(RPSystemBroadcastPickerViewのbuttonのアクション)で`buttonPressed()`という記述を見たことがあり、それ以来Pressedを使うようにしています。

2022-08-06 03:58 UTC, MasakazOzaki commented on delegate/delegate/CollectionViewCellDelegate.swift
> +protocol CollectionViewCellDelegate {
@risako070310 このprotocolはAnyObjectに準拠してあげると良きです！以前はclassを使用していました。
```suggestion
protocol CollectionViewCellDelegate: AnyObject {
```

2022-08-06 03:58 UTC, MasakazOzaki commented on delegate/delegate/CollectionViewCellDelegate.swift
> +    func buttonTapAction()
@risako070310 上述の通り、命名をいい感じにしていただけると嬉しいです！

2022-08-06 03:58 UTC, MasakazOzaki commented on delegate/delegate/ViewController.swift
> +    @IBOutlet weak var collectionViewFlowLayout: UICollectionViewFlowLayout!
@risako070310 weakつけてるの丁寧でいいね！業務のコードでは `@IBOutlet private weak var`などとweakを記述します。

なんだけど、toyboxではわかりやすさ重視なのでLife is Tech!の他の教科書と揃えてweakを削除していただけるととても助かりーみんです！

```suggestion
    @IBOutlet var fruitsCollectionView: UICollectionView!
    @IBOutlet var collectionViewFlowLayout: UICollectionViewFlowLayout!
```

2022-08-06 03:58 UTC, MasakazOzaki commented on delegate/delegate/ViewController.swift
> +        collectionViewFlowLayout.estimatedItemSize = CGSize(width: UIScreen.main.bounds.size.width, height: 50)
@risako070310 viewDidLoadが肥大化してしまうとみにくくなってしまうのでdelegateのセット、registerなどはdidSetで行うようにすると見やすなります。細かいですが修正お願いします🙏

2022-08-06 03:58 UTC, MasakazOzaki commented on delegate/delegate/ViewController.swift
> +    let fruitsList: [String] = ["りんご🍎", "ぶどう🍇", "みかん🍊", "いちご🍓", "さくらんぼ🍒"]
絵文字が入っててかわちくて良きですね🥰

2022-08-06 03:58 UTC, MasakazOzaki commented on delegate/delegate/CollectionViewCell.swift
> +    @IBOutlet weak var fruitButton: UIButton!
@risako070310 こちらも業務ではないのでweak削除しちゃいましょう〜

2022-08-06 04:00 UTC, MasakazOzaki commented on delegate/delegate/CollectionViewCell.swift
> +        fruitButton.layer.cornerRadius = 5
@risako070310 awakeFromNibはViewControllerでいうところのviewDidLoadなのでこの辺の見た目の調整もdidSetに移動しちゃいましょう。

cornerRadiusなど、数値を指定する場合は8の倍数、8じゃ大きすぎる場合は4, 2を使うことが多いんだけど今回5にした意図ってあったりするかな？

ちなみに、世の中の大体のものは8の倍数になっているので8の倍数にしとくと他のものとの差が少なくて違和感が少なく見れるという利点があります。

2022-08-06 04:10 UTC, risako070310 commented on delegate/delegate/CollectionViewCell.swift
> +        cellDone?()
これでタップされたButtonのCellIndexをindexPathに流すために書いたのですが、必要ではないのでしょうか？それかもっといい別の書き方があれば知りたいです…TT
CollectionView.swift
```
cell.cellDone = { [weak self] in
    self?.selectedCellIndex = indexPath
}
```

2022-08-06 04:24 UTC, risako070310 commented
@MasakazOzaki レビューありがとうございます！更新しました！

2022-08-06 06:39 UTC, MasakazOzaki requested changes
修正ありがとう！細かいところとindexの部分、再度修正お願いいたします🙇‍♂️🙇‍♂️

2022-08-06 06:39 UTC, MasakazOzaki commented on delegate/delegate/Assets.xcassets/CollectionViewExtension.swift
> +//  CollecitonViewExtension.swift
ファイル名なのですが、Swiftでは特定のクラスのextensionはViewController+CollectionViewDelegate.swiftのようにすることが多いです！

2022-08-06 06:39 UTC, MasakazOzaki commented on delegate/delegate/Assets.xcassets/CollectionViewExtension.swift
> +        }
cellにIndexを伝えておきたい場合は、cellにindexの変数を持たせて、ここで代入しておくと使えるよ。
cell.index = indexPathみたいなイメージです

2022-08-06 06:39 UTC, MasakazOzaki commented on delegate/delegate/Assets.xcassets/CollectionViewExtension.swift
> +        }
また、delegateメソッドの引数にindexPathを指定しておくことでcellからviewcontrollerにdelegateでボタンのアクションを渡すときもindexも一緒に送ることができます

2022-08-08 04:24 UTC, risako070310 commented
@MasakazOzaki レビューお願いします！

2022-08-08 09:28 UTC, MasakazOzaki requested changes
@risako070310 修正ありがとう！すごく良くなってきています。最後に数点、修正お願いします🙇‍♂️

2022-08-08 09:28 UTC, MasakazOzaki commented on delegate/delegate/CollectionViewCellDelegate.swift
> +    func buttonPressed(indexPath: Int)
@risako070310 こちら、indexPathを引数にするのであれば、IndexPath型をそのまま渡してしまう方が良さそうです！

IndexPath型にはsectionやrowの複数の種類のデータを保持しているので例えばsectionが0でrowが0, sectionが1でrowが0は別のcellですがDelegateメソッドの中でrowだけ渡してしまうとsectionを複数持つ場合に表示がおかしくなってしまいます＞＜

2022-08-08 09:28 UTC, MasakazOzaki commented on delegate/delegate/ViewController+CollectionViewDelegate.swift
> +        cell.index = indexPath.row
@risako070310 こちら上記の通り、indexPathそのまま渡すのをお勧めします！

2022-08-08 09:28 UTC, MasakazOzaki commented on delegate/delegate/ViewController.swift
> +    var selectedCellIndex: IndexPath?
@risako070310 ここで宣言してくれてる`selectedCellIndex`ってどこかで使ってるのかな。。？見つけられませんでした😖もし使ってなかったら削除お願いします🙇

2022-08-08 09:28 UTC, MasakazOzaki commented on delegate/delegate/ViewController.swift
> +            collectionViewFlowLayout.estimatedItemSize = CGSize(width: UIScreen.main.bounds.size.width, height: 50)
@risako070310 こちらのHeight指定が50なのは何か意図があったりするかな、、？
もし何もなければ44に変更していただけると助かります。(iOSではList形式の最小のheightは44という慣習があります。設定アプリのリストとかは44)もし、44に収まらなければ48とかの8の倍数にしていただけるととても嬉しいです

2022-08-08 10:20 UTC, risako070310 commented
@MasakazOzaki 何度もお手数おかけしてます、こちらレビューお願いします！ 
ef0b4687144674b0b2538dc0d2302584de92ac57

2022-08-08 10:58 UTC, MasakazOzaki approved these changes
@risako070310 LGTM! 🎉🎉お疲れ様でした！
ありがとう！

2022-08-08 10:58 UTC, merged