UNUserNotificationのtoyにReadmeとコードのコメントを追加
lifeistech/toybox pull request #137
Opened 2022-08-09 23:30 UTC by risako070310

Closed #124

2022-08-16 05:07 UTC, MasakazOzaki requested changes
@risako070310 PRありがとう！
コメントしました！修正よろしくお願いします🙏

2022-08-16 05:07 UTC, MasakazOzaki commented on UNUserNotification/UNUserNotification/ViewController.swift
>              ("Life is Tech! 大阪オフィス", CLLocationCoordinate2D(latitude: 34.70493918, longitude: 135.50383534))
ロケーション系もコメントで説明するとさらに良きです

2022-08-16 05:07 UTC, MasakazOzaki commented on UNUserNotification/README.md
> +- [for](https://github.com/lifeistech/toybox/tree/main/for)
位置情報とか使ってるので関連にMapKitとか出したいですね(MapKitはまだ製作中なので今回は入れずにIssueに追加しておいて欲しいです)

2022-08-20 03:54 UTC, risako070310 commented
@MasakazOzaki 再度レビューお願いします

2022-08-22 23:57 UTC, MasakazOzaki requested changes
PRありがとう！
コメントしました！
修正お願いいたします🙏

2022-08-22 23:57 UTC, MasakazOzaki commented on UNUserNotification/UNUserNotification/NotificationManager.swift
> +    //アラートウィジェットで選択した通知のリクエストを登録
アラートウィジェット -> アラートにしてもらえると助かります。
あとこのメソッドはsetTimeIntervalNotificationがコールされたらどのタイミングでも実行されるのでアラート関連の記述は削除してこのメソッドが"いつ使われるかではなく", "何をするのか"書いていただけると助かります！

2022-08-22 23:57 UTC, MasakazOzaki commented on UNUserNotification/UNUserNotification/NotificationManager.swift
> +    //アラートウィジェットで設定した日時の通知のリクエストを登録
同様に、
アラートウィジェット -> アラートにしてもらえると助かります。
あとこのメソッドはsetTimeIntervalNotificationがコールされたらどのタイミングでも実行されるのでアラート関連の記述は削除してこのメソッドが"いつ使われるかではなく", "何をするのか"書いていただけると助かります！

2022-08-22 23:57 UTC, MasakazOzaki commented on UNUserNotification/UNUserNotification/NotificationManager.swift
> +    //アラートウィジェットで設定した場所の通知のリクエストを登録
同様に
アラートウィジェット -> アラートにしてもらえると助かります。
あとこのメソッドはsetTimeIntervalNotificationがコールされたらどのタイミングでも実行されるのでアラート関連の記述は削除してこのメソッドが"いつ使われるかではなく", "何をするのか"書いていただけると助かります！

2022-08-22 23:57 UTC, MasakazOzaki commented on UNUserNotification/UNUserNotification/NotificationManager.swift
> +    //アラートウィジェットで選択した通知のリクエストを登録
わかりにくいな、アラートに関して記述したいならアラートウィジェット-> アラートにするんだけど、今回はアラートの物自体を削除したいということです！

2022-08-22 23:57 UTC, MasakazOzaki commented on UNUserNotification/UNUserNotification/ViewController.swift
> +            //場所情報を追加
場所情報 -> 位置情報の方がいいかもしれない！

2022-08-23 07:10 UTC, risako070310 commented on UNUserNotification/UNUserNotification/NotificationManager.swift
> +    //アラートウィジェットで選択した通知のリクエストを登録
アラートの物自体ってどういうことですか…

2022-09-02 07:44 UTC, MasakazOzaki approved these changes

2022-09-02 07:44 UTC, merged