MKMapViewのtoyを追加
lifeistech/toybox pull request #143
Opened 2022-08-12 12:26 UTC by igaryo0506

## 概要
MapKitを使って、緯度経度で指定した座標のMapを表示

## 見た目
![image](https://user-images.githubusercontent.com/63948210/184353579-e0c12c99-c34c-4917-b1df-70efeb27bf3d.png)

2022-08-12 12:33 UTC, igaryo0506 commented
どれくらいまで作るか困っちゃったのでとりあえず最小限だけ作ってプルリク出してみちゃいました。
レビューお願いします。

2022-08-16 05:12 UTC, MasakazOzaki requested changes
@igaryo0506 初PRありがとう！とても良くできています！

ピンを置くとか、マップの中心をどの緯度軽度にするか程度は追加してもいいかと思ったのでそちらのコードも追加お願いします！
二箇所、whitespaceの除去もお願いします！

2022-08-16 05:12 UTC, MasakazOzaki commented on MKMapView/MKMapView/ViewController.swift
> +
@igaryo0506 不要なwhitespaceは消しておきましょう！

2022-08-16 05:12 UTC, MasakazOzaki commented on MKMapView/MKMapView/ViewController.swift
> +
@igaryo0506 不要なwhitespaceは消しておきましょう！

2022-08-20 04:27 UTC, igaryo0506 commented
Pinの追加、WhiteSpaceの削除完了しました。

2022-08-20 04:49 UTC, igaryo0506 commented
余計なファイルも変更していたのでプッシュし直しました

2022-08-20 05:12 UTC, igaryo0506 commented
現在地を取得する機能も欲しいだろうなぁと思ったので追加しました。

2022-08-20 05:12 UTC, igaryo0506 commented
@MasakazOzaki Reviewお願いします

2022-09-02 07:46 UTC, MasakazOzaki approved these changes
LGTM！！🎉🎉🎉PRありがとう！

2022-09-02 07:46 UTC, merged