UIImagePicker
lifeistech/toybox pull request #147
Opened 2022-08-18 08:47 UTC by risako070310

close #125

2022-09-02 07:56 UTC, MasakazOzaki requested changes
@risako070310 
PRありがとう！
とてもわかりやすく説明されていると思います。少しだけ修正点があるので確認お願いします！🥺

あと、カメラとフォトライブラリのボタンをUIButtonConfiguration使って関連リンク増やしたりするのもありかなーと思ったんだけどどうだろう。余裕があったらサクッと変えていただけるととても嬉しいです🙏

2022-09-02 07:56 UTC, MasakazOzaki commented on UIImagePicker/README.md
> +UIImagePickerは、端末のカメラで撮影した写真、またはフォトライブラリにある写真を取得します。`.sourceType = .camera`でカメラ撮影を、`.sourceType = .photoLibrary`でメディアソースから写真を取得することができます。使用するためには、端末にカメラへのアクセスと写真へのアクセス権限をリクエストする必要があります。
細かいところで申し訳ないんだけど、
`メディアソース→カメラロール、`

`端末にカメラへのアクセスと写真へのアクセス権限をリクエスト → 端末にカメラへのアクセスと写真へのアクセス権限をInfo.plistからリクエスト`
に変更していただけるととても助かりーみんです！

2022-09-02 07:56 UTC, MasakazOzaki commented on UIImagePicker/README.md
> +2. Main.storyboardにImageViewを配置します
```suggestion
2. Main.storyboardにUIImageViewを配置します

2022-09-02 07:56 UTC, MasakazOzaki commented on UIImagePicker/README.md
> +2. ViewController.swiftから`UIImagePickerController()`で参照することができます
参照するっていう表現が少し難しい気がしました。
```suggestion
サンプルコードの通り、ViewController.swiftから`UIImagePickerController()`を用いて画像を取得します。

2022-09-02 07:59 UTC, risako070310 commented
@MasakazOzaki このPR内で完結しちゃっていいならなおしますー！別でPR立てるなら一旦issue追加でいいですか？

2022-09-03 01:54 UTC, risako070310 commented
@risako070310 UIButtonConfigurationに変更、さらにReadmeとgifも更新したのでご確認よろしくお願いします

2022-10-27 02:55 UTC, MasakazOzaki approved these changes

2022-10-28 11:06 UTC, merged