UICalendarViewのToyにReadmeとコメントを追加
lifeistech/toybox pull request #148
Opened 2022-08-22 12:37 UTC by risako070310

close #126

2022-09-02 08:03 UTC, MasakazOzaki requested changes
LGTM with nits !
すごく丁寧でとても良きです！
一点だけ、storyboardからは追加できない点だけ追加お願いします！

2022-09-02 08:52 UTC, risako070310 commented
@MasakazOzaki 更新Done!再度レビューお願いします

2022-09-02 11:17 UTC, MasakazOzaki requested changes
@risako070310 修正ありがとう！何度もごめんなさい！状況がすぐ変わりそうなものを残しておくと負債になってしまうので変わっても大丈夫な表記にしていきたいです。(すぐリリース版になるので)

2022-09-02 11:17 UTC, MasakazOzaki commented on UICalendarView/README.md
> +UICalendarViewはカレンダーを表示し、日付を1日または複数日選択することができます。フォントの種類や日付の文字色の変更、SFSymbolを表示したりなどカレンダーの見た目を簡単にカスタマイズすることもでき、イベントなどの予定の表示も可能です。こちらはiOS16から使用できるコンポーネントとなっています。現状は、Xcode betaのみでの動作かつ、Storyboardからレイアウトに
@risako070310 修正ありがとう！丁寧にbetaのことも書いてく入れていてとてもいいんだけど、来週にはこbetaじゃなくなってしまうから、`Xcode 14 以上、iOS 16以上で動作`というふうにした方がとても良いかもしれないです！

2022-09-03 02:00 UTC, risako070310 commented on UICalendarView/README.md
> +UICalendarViewはカレンダーを表示し、日付を1日または複数日選択することができます。フォントの種類や日付の文字色の変更、SFSymbolを表示したりなどカレンダーの見た目を簡単にカスタマイズすることもでき、イベントなどの予定の表示も可能です。こちらはiOS16から使用できるコンポーネントとなっています。現状は、Xcode betaのみでの動作かつ、Storyboardからレイアウトに
間違いないですね。。。直します

2022-09-03 02:01 UTC, risako070310 commented
@MasakazOzaki こちらで！お願いします！

2022-10-05 06:06 UTC, MasakazOzaki requested changes
@risako070310 コメントとReadmeは良いのですが、コード自体がちょっとヤバめなので直していただけると助かります、、、、

担当外のところをここのPRでお願いしてしまい申し訳ない」

2022-10-05 08:23 UTC, risako070310 commented on UICalendarView/UICalendarView/ViewController.swift
>      }
@MasakazOzaki  これって値のセットの時めちゃめちゃOptional状態なんだけどunwrapして代入しちゃっていいやつ？？？

2022-10-27 02:54 UTC, MasakazOzaki approved these changes

2022-11-01 07:35 UTC, kyoya1123 reviewed
@risako070310 
コメントしました！
READMEなどは問題ないです！

2022-11-01 07:35 UTC, kyoya1123 commented on UICalendarView/UICalendarView/ViewController.swift
> +    var calendarView: UICalendarView?
ここ、optionalで宣言する必要はないから
`var calendarView: UICalendarView!`
にしちゃって下さい！

2022-11-01 07:35 UTC, kyoya1123 commented on UICalendarView/UICalendarView/ViewController.swift
> +        view.addSubview(calendarView!)
ここまでを `setupCalendarView()` みたいな関数に切り出してもいいかも

2022-11-01 07:43 UTC, risako070310 commented
@kyoya1123 再度ご確認お願いします

2022-11-01 07:47 UTC, kyoya1123 commented
LGTM!

2022-11-01 07:48 UTC, merged