delegateのtoyにReadme,　gif,コードのコメントを追加
lifeistech/toybox pull request #149
Opened 2022-08-23 07:02 UTC by risako070310

2022-09-02 13:31 UTC, MasakazOzaki requested changes
@risako070310 PRありがとう！とても難しいところなのに丁寧にかいてくれて助かります。
何点かコメントしたので確認お願いします🙏

2022-09-02 13:31 UTC, MasakazOzaki commented on delegate/README.md
> +    定義したデリゲートメソッドの処理を実装します。
@risako070310 ここの文章すごく難しくなってしまってるからすこし噛み砕いてみても良さそうかもしれない！こんなのはどうだろう。私もこれはうまく日本語で説明するのすごく難しいな。。変なところ教えてください🙏もっといい感じに説明したいな
```suggestion
1. protocol  
     任せる処理の形をプロトコル(インタフェー　ス)として定義します。
    プロトコルはこんな変数や関数がありますという定義で実際の関数の中身を実装したりしない外側の部分です
 2. 処理を任せるクラス  
     ボタンを押された時などにデリゲートで実装した処理を呼び出します。その際にprotocolを定義したクラスのインスタンスを変数delegateに設定します。
 3. 処理を任されるクラス  
     定義したデリゲートメソッドの処理を実装します。

2022-09-02 13:31 UTC, MasakazOzaki commented on delegate/delegate/CollectionViewCellDelegate.swift
> +//protocolで任せるデリゲートメソッドの定義(ここでは定義のみで処理の実装は行わない)
定義のみで処理の実装は行ないわないという説明があるのとてもGoodです

2022-09-02 13:31 UTC, MasakazOzaki commented on delegate/delegate/ViewController.swift
> +            //CollectionViewCell.xibで作成したセルのレイアウトをCollectionViewにセット
ここではCollectionViewCell.xibで指定したレイアウトをセットしているのではななくて、CollectionViewCellのインスタンス自体を登録しています。
ここに登録することでReuseQueueにCellが登録されてセルが使いまわされるのでメモリの消費を抑えることができます。

2022-09-20 09:55 UTC, risako070310 commented on delegate/README.md
> +    定義したデリゲートメソッドの処理を実装します。
protocolの説明の中にdelegateという単語が出てこなくなるとdelegateの存在って結局protocolやん、、、ってなる気がして(私は最初そう思って)いたので「デリゲートメソッドとして定義」という日本語を使ったんだけどどうだろうか…定義だけで関数の中身は実装しないという説明は必要ですね

2022-09-20 09:56 UTC, risako070310 commented
@MasakazOzaki Readmeの表現、私なりに更新したので最善の説明を見つけたいです。。。レビューお願いします

2022-10-05 04:27 UTC, MasakazOzaki requested changes
@risako07031 READMEコメントありがとう！
とても丁寧でいい感じです！少しだけ修正点があったので修正お願いします！

2022-10-05 08:16 UTC, risako070310 commented
@MasakazOzaki doneです

2022-10-27 02:54 UTC, MasakazOzaki approved these changes

2022-10-28 11:19 UTC, kyoya1123 approved these changes

2022-10-28 11:19 UTC, merged