Feature/Generics
lifeistech/toybox pull request #153
Opened 2022-08-30 15:57 UTC by yukiny0811

GenericsのToyです

2022-09-01 13:57 UTC, yukiny0811 commented
ちょっと機能が少なすぎるような気がするのでもっと必要であれば言ってください！

2022-10-05 03:36 UTC, MasakazOzaki requested changes
@yukiny0811 PRありがとう！ゆるゆるらしい面白いGenericsの示し方になっていてとても良いですねー！

参照と値の`&`だけ、なぜ&が必要なのかだけコメントアウトで残しておいていただけると助かります🙏(README担当者が見落とさないように)

修正点、細かいところだけお願いしますー><><

2022-10-05 03:36 UTC, MasakazOzaki commented on Generics/Generics/ViewController.swift
> +import Foundation
@yukiny0811 import UIKitをしているときはFoundationは書かなくていいので削除をお願いしますー

2022-10-05 03:36 UTC, MasakazOzaki commented on Generics/Generics/ViewController.swift
> +    @IBOutlet var label: UILabel!
細かくて申し訳ないんだけど、L11とL12の間は可読性のために改行入れときましょうか

2022-10-05 03:36 UTC, MasakazOzaki commented on Generics/Generics/ViewController.swift
> +    override func viewDidLoad() {
ここも改行入れておきましょう

2022-10-05 03:36 UTC, MasakazOzaki commented on Generics/Generics/ViewController.swift
> +        })
ここ、Trailing Closureという機能を使うともう少し綺麗に描けるのでこのような形にしていただけると嬉しいです🥺
```suggestion
        UIView.animate(withDuration: 1.0) {
            self.addValueToTwoElement(&self.label.layer.position.y, &self.label.transform.tx, 100)
        } completion: { _ in
            self.addValueToTwoElement(&self.count1, &self.count2, 100)
            self.label.text = String(self.count1) + "," + String(self.count2)
        }
```

2022-10-05 03:36 UTC, MasakazOzaki commented on Generics/Generics/ViewController.swift
> +    func addValueToTwoElement<T: AdditiveArithmetic>(_ a: inout T, _ b: inout T, _ value: T) {
```suggestion 
    }

    func addValueToTwoElement<T: AdditiveArithmetic>(_ a: inout T, _ b: inout T, _ value: T) {
```

2022-10-27 02:54 UTC, MasakazOzaki approved these changes

2022-10-28 11:16 UTC, merged