about toyboxとScrapboxへのリンクをMain Readmeに追加
lifeistech/toybox pull request #165
Opened 2022-09-10 08:50 UTC by risako070310

2022-09-11 17:07 UTC, MasakazOzaki requested changes

2022-09-11 17:07 UTC, MasakazOzaki commented on README.md
> +Life is Tech! iPhoneコースのサンプルコード集プロジェクトです。Swiftにはどんな技術があるのか、どんなコードを書けばどのように動くのか見て、触ってみることができます。コードの詰め合わせという意味から、そしてたくさん遊んで欲しいという思いを込めて、おもちゃ箱のtoyboxと名付けられました🎉Swiftの機能がコンポーネントごとにtoyとして分かれていて、それぞれXcode P
```suggestion
Life is Tech! iPhoneアプリプログラミングコースのサンプルコード集プロジェクトです。Swiftにはどんな技術があるのか、どんなコードを書けばどのように動くのか見て、触ってみることができます。
　コードの詰め合わせという意味から、そしてたくさん遊んで欲しいという思いを込めて、おもちゃ箱のtoyboxと名付けられました🎉
　Swiftの機能がコンポーネントごとにtoyとして分かれていて、それぞれXcode Projectが作られています👀  
```

2022-09-11 17:07 UTC, MasakazOzaki commented on README.md
> +2. ダウンロードしたzipファイルをダブルクリックで解凍します
`解凍`→`展開`
macだと最近展開が勝手にされるから書かなくていいかもしれない。(流石にzip展開ぐらい知ってる人がToybox使って欲しい)

2022-09-11 17:07 UTC, MasakazOzaki commented on README.md
> +4. フォルダ内に入っている`.xcodeproject`の拡張子のファイルをダブルクリックするとXcodeが開きます
```suggestion
4. フォルダ内に入っている`.xcodeproj`の拡張子のファイルをダブルクリックするとXcodeが開きます
```

2022-09-15 06:55 UTC, risako070310 commented
@MasakazOzaki 修正しましたあ！レビューお願いします

2022-10-04 16:19 UTC, MasakazOzaki requested changes
@risako070310 ありがとう！
とても良くなったと思います！
トップページなのでつい厳しめにみてしまっていますが少しだけ直してもらえると助かります＞＜

2022-10-04 16:19 UTC, MasakazOzaki commented on README.md
> +[Scrapbox](https://scrapbox.io/toybox-ios/)からtoyごとのスクリーンレコードgifの一覧・toyの相互関係を見ることができます！
```suggestion
[Scrapbox](https://scrapbox.io/toybox-ios/)からtoyの一覧・toyの相互関係を見ることができます！
```
スクリーンレコードとか、gifであるとかそういう情報は製作者側の都合でみる人にはあんまり関係ない情報なので省いてしまっても問題ないかもです！

2022-10-04 16:19 UTC, MasakazOzaki commented on README.md
> +5. READMEにそのtoyの技術について、概要や実装方法が記載されています
4と5の間で、ネットからダウンロードしたものだけど開いて大丈夫？みたいな警告が出ると思うから、警告が出た場合は Trust And Openを押すみたいな文を追加したらさらに丁寧になると思いました！

2022-10-04 16:22 UTC, risako070310 commented on README.md
> +5. READMEにそのtoyの技術について、概要や実装方法が記載されています
zipでダウンロードするとそうやって出るのか、いつも気にしてなかったなぁ　直します

2022-10-04 16:26 UTC, risako070310 commented
@MasakazOzaki 更新どね

2022-10-04 16:46 UTC, MasakazOzaki approved these changes
LGTM!ありがとう！

2022-10-04 16:46 UTC, merged