Do Try Catch
lifeistech/toybox pull request #166
Opened 2022-09-19 11:23 UTC by yukiny0811

2022-10-04 15:55 UTC, MasakazOzaki requested changes
@yukiny0811 PRありがとう！エラーハンドリングができていてとてもいいと思いました！

メンバーレベルのオリジナル開発で一番身近なdo try catchを使いそうな場面はasync awaitのところだと思うのでその例も追加していただけるととても嬉しいです！

2022-10-04 15:55 UTC, MasakazOzaki commented on DoTryCatch/DoTryCatch/ViewController.swift
> +    func setColor(r: CGFloat, g: CGFloat = 1.0, b: CGFloat = 1.0) throws {
@yukiny0811 メソッドのあとは一行emptyLineを入れる慣習があるので追加していただけると助かります！

2022-10-04 15:55 UTC, MasakazOzaki commented on DoTryCatch/DoTryCatch/ViewController.swift
> +    @IBAction func setFromButton(_ sender: UIButton) {
@yukiny0811 メソッドのあとは一行emptyLineを入れる慣習があるので追加していただけると助かります！

2022-10-04 15:55 UTC, MasakazOzaki commented on DoTryCatch/DoTryCatch/ViewController.swift
> +}
@yukiny0811 Alertで文字を決めうつんじゃなくて、エラーの定義のところにメッセージを定義してlocalizedDescriptionで呼び出せるようにした方が綺麗な気がしたのでもしよければ変更をお願いします！

2022-10-05 07:19 UTC, yukiny0811 commented
Async Awaitについては別でToy作った方がいいかな、って思うのですがどうでしょう？

2022-10-20 10:47 UTC, kyoya1123 commented
@yukiny0811 
LGTM!
async/awaitは別toyにして、前提(関連)にこれを入れよう

2022-10-20 10:47 UTC, kyoya1123 approved these changes

2022-10-20 10:48 UTC, merged