UIHostingConfigurationのtoyにReadmeとコメントを追加
lifeistech/toybox pull request #170
Opened 2022-09-20 15:02 UTC by risako070310

Close #161

2022-10-04 16:07 UTC, MasakazOzaki requested changes
@yukiny0811 PRありがとう！とても丁寧に書かれていてとても良いと思います！

何点かコメントしたので直してもらえると助かります！

2022-10-04 16:22 UTC, risako070310 commented
@MasakazOzaki 更新しました

2022-10-27 02:53 UTC, MasakazOzaki approved these changes

2022-10-28 11:12 UTC, kyoya1123 approved these changes

2022-10-28 11:13 UTC, merged