SwiftChartsのREADMEを追加
lifeistech/toybox pull request #172
Opened 2022-09-27 13:38 UTC by yukiny0811

2022-10-04 15:47 UTC, MasakazOzaki requested changes
@yukiny0811 READMEありがとう！
少しコメントしました。修正お願いします！

2022-10-04 15:47 UTC, MasakazOzaki commented on SwiftCharts/README.md
> +Swift Chartsはインフォグラフィックス作成用のSwiftUIフレームワークです。
@yukiny0811 インフォグラっフィクスというのは数字だけじゃわかりづらいのをグラフとかを用いたポスターみたいなものを指すからここでは普通に
```suggestion
Swiftでグラフを作るためのSwiftUIのフレームワークです。
```
とかでいいと思いました

2022-10-20 11:00 UTC, kyoya1123 approved these changes
LGTM!

2022-10-27 02:53 UTC, MasakazOzaki approved these changes

2022-10-28 11:03 UTC, merged