Feature/singleton
lifeistech/toybox pull request #184
Opened 2024-02-15 23:59 UTC by AtsushiHosaka

- 画面遷移時に値を受け渡す方法としてSingletonを用いています
- READMEで、シングルトンがどのようなものか簡単に説明してみました（内容が適切かどうかわからないのでご確認お願いしたいです）

2024-02-16 10:42 UTC, moyotsukai commented
早速取り掛かってくれてありがとう！
いくつかフィードバックあるので確認お願いします！

- 僕がTrelloに値渡しがどうのって書いちゃったけど、値渡しに関係なくシングルトンの使い方を書けるといいかも！
- もう少しプロパティの数があった方がメンバーにとって実用的に感じるかも。
- 結構上級者が読むものだと思うので、アクセス修飾子つけるといいかも！

2024-02-20 09:49 UTC, moyotsukai requested changes
ごめん、意見が変わっちゃって申し訳ないんだけど、ToyBoxの他のアプリを見ると、トピックに関連しないボタンデザインや背景色はシステムのものを利用しているので、やっぱりそのデザインに統一してもらってもいいかな？
- ボタンデザインや背景色はシステムのものを利用
- TabBarにアイコンをつける
- Readmeファイルの配置を1個上の階層にする
をお願いしてもいいかな？

2024-02-20 10:44 UTC, nokonoko2057 commented on Singleton/Singleton/TextDataModel.swift
> +class TextDataModel {
Singletonを扱うクラスで〜Modelってあんまり言わないから、
〜Managerとかがいいかな
このクラス自体が、テキストのデータを記録したり、履歴を保存・取得する役割を持ってるので、設計観点でもModelとして扱わなそう

2024-02-20 10:44 UTC, nokonoko2057 commented on Singleton/Singleton/TextDataModel.swift
> +//MARK: SegueStartViewControllerとSegueDestinationViewControllerのデータを管理します
やってることはそうなんだけど、このクラス自体はSegueStartViewControllerにもSegueDestinationViewControllerにも依存してないから、もう少し広い言い回しが嬉しい！！

2024-02-20 10:44 UTC, nokonoko2057 commented on Singleton/Singleton/README.md
> +あるクラス（このプロジェクトでは、TextDataModel）に、staticというものを使ってそのクラス自身のインスタンスを持たせると、（static let shared = TextDataModel()) どんな場所からでもただ一つのインスタンスにアクセスすることができます。（TextDataModel.sharedと呼び出せる）
ここはプロジェクトの中身を知らない状態で読むと思うので、
クラス名はなくていいかも

2024-02-20 10:44 UTC, nokonoko2057 commented on Singleton/Singleton/README.md
> +また、シングルトンがついているクラスの中で用いるメソッド（関数）はprivateというアクセス修飾子をつけています。これにより、シングルトンを用いないとメソッドを使えないようになり、不要な場所から間違って関数が呼び出されることをなくし、そのメソッドがどのような役割かをわかりやすくすることができます。
これは、シングルトンの説明ではなくて、コードの説明なのでコメントアウトでつけてもらったコメントだけで良さそう！

2024-02-20 10:44 UTC, nokonoko2057 commented on Singleton/Singleton/README.md
> +シングルトンはデザインパターンと呼ばれるものの一つで、他にも様々なものがあります。興味があれば、「DI」なども調べてみると、さらに綺麗なコードが書けるようになっていきます！
めっちゃいいね！ 👍 
DIだけだと辿りつけない可能性があるので、DI(Dependency Injection) とか記載してあげると丁寧だね！

2024-02-28 15:26 UTC, nokonoko2057 approved these changes

2024-03-01 09:03 UTC, merged