UITabBarControllerのReadmeを追加
lifeistech/toybox pull request #45
Opened 2022-07-02 15:21 UTC by risako070310

2022-07-03 07:52 UTC, MasakazOzaki commented
@risako070310 修正お願いしますー

2022-07-04 03:59 UTC, risako070310 commented
@MasakazOzaki Readme修正しましたー

2022-07-04 12:07 UTC, MasakazOzaki commented on UITabBarController/README.md
> +UITabBarControllerは、複数のViewControllerを管理し、選択によって表示を切り替えることができます。
@risako070310 こちら対応お願いします！

2022-07-04 12:08 UTC, MasakazOzaki commented on UITabBarController/README.md
> +- LINEのBottomメニュー
@risako070310 こちらも対応お願いします！

2022-07-04 12:11 UTC, MasakazOzaki commented
@risako070310 忙しいところごめん！コメントのところ修正お願いします！

2022-07-04 12:42 UTC, risako070310 commented on UITabBarController/README.md
> +- LINEのBottomメニュー
めっちゃ見落としでした広義の今日中にやります😿

2022-07-04 17:03 UTC, risako070310 commented
@MasakazOzaki 修正しました d459a706c0eaf81e72e810ecab62c32879995770

2022-07-07 08:13 UTC, MasakazOzaki approved these changes
LGTM！
たくさん修正に出してしまって申し訳なかった！
お疲れ様でした！ありがとう！

2022-07-07 08:13 UTC, MasakazOzaki commented
@nokonoko2057 こちらもレビューお願いいたします

2022-07-07 11:41 UTC, nokonoko2057 requested changes
@risako070310 あれ、これってプロジェクトファイルから参照されてる？

2022-07-08 07:16 UTC, risako070310 commented
@nokonoko2057 プロジェクトファイルから参照されてなかったです！追加しました>< d9c10aff06c0007edd7e03b537a7cf84762289ba

2022-07-08 07:17 UTC, nokonoko2057 approved these changes
@risako070310 ありがとうー！

2022-07-08 07:18 UTC, merged